Repository MoodBuddy/Server, pull requests merged in 2024-11, with the labels that each got.

#14 [Refactor] 커스텀 예외를 리팩토링
  src/main/generated/moodbuddy/moodbuddy/domain/bookMark/mapper/BookMarkMapperImpl.java
  src/main/generated/moodbuddy/moodbuddy/domain/diary/mapper/DiaryMapperImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/letter/service/LetterServiceImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/user/controller/UserApiController.java
  src/main/java/moodbuddy/moodbuddy/domain/user/facade/UserFacade.java
  src/main/java/moodbuddy/moodbuddy/domain/user/facade/UserFacadeImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/user/service/UserService.java
  src/main/java/moodbuddy/moodbuddy/domain/user/service/UserServiceImpl.java
  src/main/java/moodbuddy/moodbuddy/global/common/exception/ApiErrorResponse.java
  src/main/java/moodbuddy/moodbuddy/global/common/exception/ApiExceptionHandler.java
  src/main/java/moodbuddy/moodbuddy/global/common/exception/MoodBuddyException.java
  src/main/java/moodbuddy/moodbuddy/global/common/exception/bookMark/BookMarkNotFoundException.java
  src/main/java/moodbuddy/moodbuddy/global/common/exception/database/DatabaseNullOrEmptyException.java
  src/main/java/moodbuddy/moodbuddy/global/common/exception/diary/DiaryInsufficientException.java
  src/main/java/moodbuddy/moodbuddy/global/common/exception/diary/DiaryNoAccessException.java
  src/main/java/moodbuddy/moodbuddy/global/common/exception/diary/DiaryNotFoundException.java
  src/main/java/moodbuddy/moodbuddy/global/common/exception/diary/DiaryTodayExistingException.java
  src/main/java/moodbuddy/moodbuddy/global/common/exception/gpt/ParsingContentException.java
  src/main/java/moodbuddy/moodbuddy/global/common/exception/letter/LetterNotFoundByIdAndUserIdException.java
  src/main/java/moodbuddy/moodbuddy/global/common/exception/letter/LetterNotFoundByIdException.java
  src/main/java/moodbuddy/moodbuddy/global/common/exception/letter/LetterNumsException.java
  src/main/java/moodbuddy/moodbuddy/global/common/exception/profile/ProfileImageNotFoundByUserIdException.java
  src/main/java/moodbuddy/moodbuddy/global/common/exception/profile/ProfileNotFoundByUserIdException.java
  src/main/java/moodbuddy/moodbuddy/global/common/exception/quddyTI/QuddyTINotFoundException.java
  src/main/java/moodbuddy/moodbuddy/global/common/exception/user/UserNotFoundByUserIdException.java
  src/main/java/moodbuddy/moodbuddy/global/common/gpt/service/GptServiceImpl.java
Labels: 🔨 Refactor, 🐶 M-ung

#19 [Refactor] Diary & BookMark API 재점검해라
  build.gradle
  src/main/generated/moodbuddy/moodbuddy/domain/bookMark/domain/QBookMark.java
  src/main/generated/moodbuddy/moodbuddy/domain/bookMark/mapper/BookMarkMapperImpl.java
  src/main/generated/moodbuddy/moodbuddy/domain/diary/domain/base/QDiary.java
  src/main/generated/moodbuddy/moodbuddy/domain/diary/mapper/DiaryMapperImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/bookMark/controller/BookMarkApiController.java
  src/main/java/moodbuddy/moodbuddy/domain/bookMark/domain/BookMark.java
  src/main/java/moodbuddy/moodbuddy/domain/bookMark/dto/response/BookMarkResToggleDTO.java
  src/main/java/moodbuddy/moodbuddy/domain/bookMark/facade/BookMarkFacade.java
  src/main/java/moodbuddy/moodbuddy/domain/bookMark/facade/BookMarkFacadeImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/bookMark/mapper/BookMarkMapper.java
  src/main/java/moodbuddy/moodbuddy/domain/bookMark/repository/BookMarkRepository.java
  src/main/java/moodbuddy/moodbuddy/domain/bookMark/repository/BookMarkRepositoryImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/bookMark/service/BookMarkService.java
  src/main/java/moodbuddy/moodbuddy/domain/bookMark/service/BookMarkServiceImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/controller/base/DiaryApiController.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/domain/base/Diary.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/dto/request/DiaryReqSaveDTO.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/dto/request/DiaryReqUpdateDTO.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/dto/response/DiaryResDetailDTO.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/dto/response/DiaryResDraftFindOneDTO.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/facade/base/DiaryFacadeImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/mapper/DiaryMapper.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/repository/base/DiaryRepository.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/repository/base/DiaryRepositoryImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/service/base/DiaryService.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/service/base/DiaryServiceImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/service/find/DiaryFindServiceImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/service/image/DiaryImageServiceImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/user/controller/UserApiController.java
  src/main/java/moodbuddy/moodbuddy/domain/user/service/UserService.java
  src/main/java/moodbuddy/moodbuddy/domain/user/service/UserServiceImpl.java
  src/main/java/moodbuddy/moodbuddy/global/common/config/SecurityConfig.java
Labels: 🐞 BugFix, 🐶 M-ung

#22 [Feature] 이미지 업로드 API 구현
  README.md
  src/main/generated/moodbuddy/moodbuddy/domain/diary/domain/image/QDiaryImage.java
  src/main/generated/moodbuddy/moodbuddy/domain/diary/mapper/DiaryMapperImpl.java
  src/main/generated/moodbuddy/moodbuddy/domain/diary/mapper/image/DiaryImageMapperImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/bookMark/repository/BookMarkRepositoryImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/controller/DiaryApiController.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/controller/image/DiaryImageApiController.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/domain/image/DiaryImage.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/dto/request/DiaryReqSaveDTO.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/dto/request/DiaryReqUpdateDTO.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/dto/response/image/DiaryImageResURLDTO.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/facade/DiaryFacade.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/facade/DiaryFacadeImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/facade/image/DiaryImageFacade.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/facade/image/DiaryImageFacadeImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/mapper/image/DiaryImageMapper.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/repository/DiaryRepositoryImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/repository/find/DiaryFindRepositoryImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/repository/image/DiaryImageRepository.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/service/image/DiaryImageService.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/service/image/DiaryImageServiceImpl.java
  src/main/java/moodbuddy/moodbuddy/global/common/cloud/ThumbnailGenerator.java
  src/main/java/moodbuddy/moodbuddy/global/common/cloud/dto/request/CloudReqDTO.java
  src/main/java/moodbuddy/moodbuddy/global/common/cloud/dto/response/CloudUploadDTO.java
  src/main/java/moodbuddy/moodbuddy/global/common/cloud/service/CloudService.java
  src/main/java/moodbuddy/moodbuddy/global/common/cloud/service/CloudServiceImpl.java
  src/main/java/moodbuddy/moodbuddy/global/common/config/AsyncConfig.java
  src/main/java/moodbuddy/moodbuddy/global/common/exception/ErrorCode.java
  src/main/java/moodbuddy/moodbuddy/global/common/exception/diaryImage/DiaryImageNotFoundException.java
Labels: ✨ Feature, 🐶 M-ung

#23 [Refactor] QuddyTI를 리팩토링
  src/main/generated/moodbuddy/moodbuddy/domain/diary/mapper/DiaryMapperImpl.java
  src/main/generated/moodbuddy/moodbuddy/domain/diary/mapper/image/DiaryImageMapperImpl.java
  src/main/generated/moodbuddy/moodbuddy/domain/quddyTI/domain/QQuddyTI.java
  src/main/generated/moodbuddy/moodbuddy/domain/quddyTI/mapper/QuddyTIMapperImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/controller/DiaryApiController.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/controller/draft/DraftDiaryApiController.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/controller/find/DiaryFindApiController.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/domain/type/DiaryEmotion.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/dto/request/DiaryReqSaveDTO.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/dto/request/DiaryReqUpdateDTO.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/facade/DiaryFacadeImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/facade/draft/DraftDiaryFacadeImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/repository/find/DiaryFindRepositoryImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/service/count/DiaryCountService.java
  src/main/java/moodbuddy/moodbuddy/domain/diary/service/count/DiaryCountServiceImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/quddyTI/controller/QuddyTIApiController.java
  src/main/java/moodbuddy/moodbuddy/domain/quddyTI/domain/QuddyTI.java
  src/main/java/moodbuddy/moodbuddy/domain/quddyTI/domain/QuddyTIStatus.java
  src/main/java/moodbuddy/moodbuddy/domain/quddyTI/domain/type/QuddyTIType.java
  src/main/java/moodbuddy/moodbuddy/domain/quddyTI/dto/response/QuddyTIResDetailDTO.java
  src/main/java/moodbuddy/moodbuddy/domain/quddyTI/facade/QuddyTIFacade.java
  src/main/java/moodbuddy/moodbuddy/domain/quddyTI/facade/QuddyTIFacadeImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/quddyTI/mapper/QuddyTIMapper.java
  src/main/java/moodbuddy/moodbuddy/domain/quddyTI/repository/QuddyTIRepository.java
  src/main/java/moodbuddy/moodbuddy/domain/quddyTI/scheduler/QuddyTIScheduler.java
  src/main/java/moodbuddy/moodbuddy/domain/quddyTI/service/QuddyTIService.java
  src/main/java/moodbuddy/moodbuddy/domain/quddyTI/service/QuddyTIServiceImpl.java
  src/main/java/moodbuddy/moodbuddy/global/common/exception/ErrorCode.java
  src/main/java/moodbuddy/moodbuddy/global/common/exception/quddyTI/QuddyTIInvalidateException.java
Labels: 🔨 Refactor, 🐶 M-ung

#29 [Fix] DiaryStatus, MoodBuddyStatus를 고려하지 못 한 에러를 해결
  src/main/java/moodbuddy/moodbuddy/domain/diary/repository/find/DiaryFindRepositoryImpl.java
Labels: 🐞 BugFix, 🐶 M-ung

#31 [Feature] 프로필 이미지 업로드 로직 구현
  src/main/generated/moodbuddy/moodbuddy/domain/diary/mapper/DiaryMapperImpl.java
  src/main/generated/moodbuddy/moodbuddy/domain/diary/mapper/image/DiaryImageMapperImpl.java
  src/main/generated/moodbuddy/moodbuddy/domain/quddyTI/mapper/QuddyTIMapperImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/profile/dto/request/ProfileReqUpdateDTO.java
  src/main/java/moodbuddy/moodbuddy/domain/profile/dto/response/ProfileResDetailDTO.java
  src/main/java/moodbuddy/moodbuddy/domain/user/controller/UserApiController.java
  src/main/java/moodbuddy/moodbuddy/domain/user/facade/UserFacade.java
  src/main/java/moodbuddy/moodbuddy/domain/user/facade/UserFacadeImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/user/service/UserService.java
  src/main/java/moodbuddy/moodbuddy/domain/user/service/UserServiceImpl.java
Labels: ✨ Feature, 🐶 M-ung

#33 [Feature] 프로필 이미지 업로드 로직 구현
  src/main/generated/moodbuddy/moodbuddy/domain/diary/mapper/DiaryMapperImpl.java
  src/main/generated/moodbuddy/moodbuddy/domain/diary/mapper/image/DiaryImageMapperImpl.java
  src/main/generated/moodbuddy/moodbuddy/domain/quddyTI/mapper/QuddyTIMapperImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/profile/dto/request/ProfileReqUpdateDTO.java
  src/main/java/moodbuddy/moodbuddy/domain/profile/dto/response/ProfileResDetailDTO.java
  src/main/java/moodbuddy/moodbuddy/domain/user/controller/UserApiController.java
  src/main/java/moodbuddy/moodbuddy/domain/user/facade/UserFacade.java
  src/main/java/moodbuddy/moodbuddy/domain/user/facade/UserFacadeImpl.java
  src/main/java/moodbuddy/moodbuddy/domain/user/service/UserService.java
  src/main/java/moodbuddy/moodbuddy/domain/user/service/UserServiceImpl.java
Labels: ✨ Feature, 🐶 M-ung

#38 [Chore] Allow Origin 추가해라 - Feature/#36
  src/main/java/moodbuddy/moodbuddy/domain/diary/controller/emotion/DiaryEmotionApiController.java
  src/main/java/moodbuddy/moodbuddy/domain/letter/controller/LetterApiController.java
  src/main/java/moodbuddy/moodbuddy/domain/user/controller/OAuthController.java
  src/main/java/moodbuddy/moodbuddy/domain/user/dto/request/UserReqLoginDTO.java
  src/main/java/moodbuddy/moodbuddy/domain/user/repository/UserRepository.java
  src/main/java/moodbuddy/moodbuddy/domain/user/service/UserService.java
  src/main/java/moodbuddy/moodbuddy/domain/user/service/UserServiceImpl.java
  src/main/java/moodbuddy/moodbuddy/global/common/config/SecurityConfig.java
Labels: 🐱 ZZAM, 🧹 Chore
